name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            artifact: kide-linux-x64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact: kide-linux-arm64
            target: aarch64-unknown-linux-gnu
          # macOS builds
          - os: macos-latest
            artifact: kide-macos-arm64
            target: aarch64-apple-darwin
          - os: macos-13  # Intel runners
            artifact: kide-macos-x64
            target: x86_64-apple-darwin
          # Windows builds (native)
          - os: windows-latest
            artifact: kide-windows-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust (with target)
      if: matrix.os != 'windows-latest'
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Install Rust (Windows native)
      if: matrix.os == 'windows-latest'
      uses: dtolnay/rust-toolchain@stable

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies (Ubuntu x64)
      if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install dependencies (Ubuntu ARM64)
      if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        # Install ARM64 cross-compilation libraries
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev:arm64 libwebkit2gtk-4.1-dev:arm64 libappindicator3-dev:arm64 librsvg2-dev:arm64
        # Set environment variables for cross compilation
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH_aarch64-unknown-linux-gnu=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV

    - name: Install Node.js dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app (Linux/macOS with target)
      if: matrix.os != 'windows-latest'
      run: npm run tauri build -- --target ${{ matrix.target }}
      
    - name: Build Tauri app (Windows native)
      if: matrix.os == 'windows-latest'
      run: npm run tauri build

    - name: Upload binaries (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/appimage/
          src-tauri/target/${{ matrix.target }}/release/bundle/deb/

    - name: Upload binaries (macOS)
      if: startsWith(matrix.os, 'macos')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/dmg/
          src-tauri/target/${{ matrix.target }}/release/bundle/macos/

    - name: Upload binaries (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          src-tauri/target/release/bundle/msi/
          src-tauri/target/release/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Rename and organize artifacts
      run: |
        # Linux x64 files
        if [ -d "kide-linux-x64" ]; then
          mkdir -p release-files
          find kide-linux-x64 -name "*.AppImage" -exec cp {} release-files/kide-linux-x64.AppImage \;
          find kide-linux-x64 -name "*.deb" -exec cp {} release-files/kide-linux-x64.deb \;
        fi
        
        # Linux ARM64 files
        if [ -d "kide-linux-arm64" ]; then
          mkdir -p release-files
          find kide-linux-arm64 -name "*.AppImage" -exec cp {} release-files/kide-linux-arm64.AppImage \;
          find kide-linux-arm64 -name "*.deb" -exec cp {} release-files/kide-linux-arm64.deb \;
        fi
        
        # macOS ARM64 files  
        if [ -d "kide-macos-arm64" ]; then
          find kide-macos-arm64 -name "*.dmg" -exec cp {} release-files/kide-macos-arm64.dmg \;
          find kide-macos-arm64 -name "*.app" -type d -exec zip -r release-files/kide-macos-arm64.app.zip {} \;
        fi
        
        # macOS x64 files
        if [ -d "kide-macos-x64" ]; then
          find kide-macos-x64 -name "*.dmg" -exec cp {} release-files/kide-macos-x64.dmg \;
          find kide-macos-x64 -name "*.app" -type d -exec zip -r release-files/kide-macos-x64.app.zip {} \;
        fi
        
        # Windows files
        if [ -d "kide-windows-x64" ]; then
          find kide-windows-x64 -name "*.msi" -exec cp {} release-files/kide-windows-x64.msi \;
          find kide-windows-x64 -name "*.exe" -not -path "*/bundle/*" -exec cp {} release-files/kide-windows-x64.exe \;
        fi
        
        ls -la release-files/ || echo "No release files found"
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        files: release-files/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}